# Generated by Django 4.0.1 on 2022-02-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matapp', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matapp.user'),
        ),
    ]
