# Generated by Django 4.0.1 on 2022-02-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matapp', '0003_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='User',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
