# Generated by Django 4.0.1 on 2022-02-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matapp', '0004_remove_recipe_user_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
